name: CI/CD Tienda Perritos - Orquestación AWS ECS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    # 1. Autenticación automática con AWS Academy usando tus GitHub Secrets
    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # 2. Login automático en Amazon ECR
    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. Compilación y subida automática del Frontend a tu ECR privado
    - name: Build y Push Frontend a ECR
      run: |
        docker build -t 974660950724.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest ./Devops4-main/frontend
        docker push 974660950724.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest

    # 4. Compilación y subida automática del Backend a tu ECR privado
    - name: Build y Push Backend a ECR
      run: |
        docker build -t 974660950724.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest ./Devops4-main/backend
        docker push 974660950724.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest

    # 5. Despliegue y actualización automática en el clúster express que creó AWS
    - name: Actualizar Servicio Express en ECS
      run: |
        aws ecs update-service --cluster cluster-tienda-perritos-1298 --service default/cluster-tienda-perritos-1298 --force-new-deployment
